export const FETCH_LIST_REQUEST = 'routes/FETCH_LIST_REQUEST';
export const FETCH_LIST_SUCCESS = 'routes/FETCH_LIST_SUCCESS';
export const FETCH_LIST_FAILURE = 'routes/FETCH_LIST_FAILURE';

export const DELETE_ROUTE_REQUEST = 'routes/DELETE_REQUEST';
export const DELETE_ROUTE_SUCCESS = 'routes/DELETE_SUCCESS';
export const DELETE_ROUTE_FAILURE = 'routes/DELETE_FAILURE';

export const FETCH_ONE_REQUEST = 'routes/FETCH_ONE_REQUEST';
export const FETCH_ONE_SUCCESS = 'routes/FETCH_ONE_SUCCESS';
export const FETCH_ONE_FAILURE = 'routes/FETCH_ONE_FAILURE';
